/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthAbcRouteImport } from './routes/_auth/abc'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as MainAboutRouteImport } from './routes/_main/about'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainParallaxRouteImport } from './routes/_main/parallax'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as MainScrollTriggerRouteImport } from './routes/_main/scroll-trigger'
import { Route as MainStoriesRouteImport } from './routes/_main/stories'
import { Route as MainTestRouteImport } from './routes/_main/test'

const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainTestRoute = MainTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainStoriesRoute = MainStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainScrollTriggerRoute = MainScrollTriggerRouteImport.update({
  id: '/scroll-trigger',
  path: '/scroll-trigger',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainParallaxRoute = MainParallaxRouteImport.update({
  id: '/parallax',
  path: '/parallax',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAboutRoute = MainAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MainRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAbcRoute = AuthAbcRouteImport.update({
  id: '/abc',
  path: '/abc',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/abc': typeof AuthAbcRoute
  '/login': typeof AuthLoginRoute
  '/about': typeof MainAboutRoute
  '/parallax': typeof MainParallaxRoute
  '/scroll-trigger': typeof MainScrollTriggerRoute
  '/stories': typeof MainStoriesRoute
  '/test': typeof MainTestRoute
  '/': typeof MainIndexRoute
}
export interface FileRoutesByTo {
  '/abc': typeof AuthAbcRoute
  '/login': typeof AuthLoginRoute
  '/about': typeof MainAboutRoute
  '/parallax': typeof MainParallaxRoute
  '/scroll-trigger': typeof MainScrollTriggerRoute
  '/stories': typeof MainStoriesRoute
  '/test': typeof MainTestRoute
  '/': typeof MainIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_main': typeof MainRouteRouteWithChildren
  '/_auth/abc': typeof AuthAbcRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_main/about': typeof MainAboutRoute
  '/_main/parallax': typeof MainParallaxRoute
  '/_main/scroll-trigger': typeof MainScrollTriggerRoute
  '/_main/stories': typeof MainStoriesRoute
  '/_main/test': typeof MainTestRoute
  '/_main/': typeof MainIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/abc'
    | '/login'
    | '/about'
    | '/parallax'
    | '/scroll-trigger'
    | '/stories'
    | '/test'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/abc'
    | '/login'
    | '/about'
    | '/parallax'
    | '/scroll-trigger'
    | '/stories'
    | '/test'
    | '/'
  id:
    | '__root__'
    | '/_auth'
    | '/_main'
    | '/_auth/abc'
    | '/_auth/login'
    | '/_main/about'
    | '/_main/parallax'
    | '/_main/scroll-trigger'
    | '/_main/stories'
    | '/_main/test'
    | '/_main/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  MainRouteRoute: typeof MainRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/test': {
      id: '/_main/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof MainTestRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/stories': {
      id: '/_main/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof MainStoriesRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/scroll-trigger': {
      id: '/_main/scroll-trigger'
      path: '/scroll-trigger'
      fullPath: '/scroll-trigger'
      preLoaderRoute: typeof MainScrollTriggerRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/parallax': {
      id: '/_main/parallax'
      path: '/parallax'
      fullPath: '/parallax'
      preLoaderRoute: typeof MainParallaxRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/about': {
      id: '/_main/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MainAboutRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/abc': {
      id: '/_auth/abc'
      path: '/abc'
      fullPath: '/abc'
      preLoaderRoute: typeof AuthAbcRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthAbcRoute: typeof AuthAbcRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAbcRoute: AuthAbcRoute,
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface MainRouteRouteChildren {
  MainAboutRoute: typeof MainAboutRoute
  MainParallaxRoute: typeof MainParallaxRoute
  MainScrollTriggerRoute: typeof MainScrollTriggerRoute
  MainStoriesRoute: typeof MainStoriesRoute
  MainTestRoute: typeof MainTestRoute
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainAboutRoute: MainAboutRoute,
  MainParallaxRoute: MainParallaxRoute,
  MainScrollTriggerRoute: MainScrollTriggerRoute,
  MainStoriesRoute: MainStoriesRoute,
  MainTestRoute: MainTestRoute,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  MainRouteRoute: MainRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
