/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParallaxRouteImport } from './routes/parallax'
import { Route as ScrollTriggerRouteImport } from './routes/scroll-trigger'

const ScrollTriggerRoute = ScrollTriggerRouteImport.update({
  id: '/scroll-trigger',
  path: '/scroll-trigger',
  getParentRoute: () => rootRouteImport,
} as any)
const ParallaxRoute = ParallaxRouteImport.update({
  id: '/parallax',
  path: '/parallax',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/parallax': typeof ParallaxRoute
  '/scroll-trigger': typeof ScrollTriggerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/parallax': typeof ParallaxRoute
  '/scroll-trigger': typeof ScrollTriggerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/parallax': typeof ParallaxRoute
  '/scroll-trigger': typeof ScrollTriggerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/parallax' | '/scroll-trigger'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/parallax' | '/scroll-trigger'
  id: '__root__' | '/' | '/about' | '/parallax' | '/scroll-trigger'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ParallaxRoute: typeof ParallaxRoute
  ScrollTriggerRoute: typeof ScrollTriggerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scroll-trigger': {
      id: '/scroll-trigger'
      path: '/scroll-trigger'
      fullPath: '/scroll-trigger'
      preLoaderRoute: typeof ScrollTriggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parallax': {
      id: '/parallax'
      path: '/parallax'
      fullPath: '/parallax'
      preLoaderRoute: typeof ParallaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ParallaxRoute: ParallaxRoute,
  ScrollTriggerRoute: ScrollTriggerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
